version: '2'
services:
  configserver:
    image: rocklee1108/confsvr:chapter3
    ports:
      - "8888:8888"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "eagle_eye_local"
