version: '2'
services:
  eurekaserver:
    image: rocklee1108/eurekasvr:chapter4
    ports: 
      - "8761:8761"
  configserver:
    image: rocklee1108/confsvr:chapter3
    ports:
      - "8888:8888"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "eagle_eye_local"
  licensingservice:
    image: rocklee1108/licensing-service:chapter3
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
