server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YimengL/config-repo.git
          search-paths: licensingservice
          username:
          password:


#server:
#  port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:///Users/liyi/Documents/Java-Workspace/confsvr/src/main/resources/config/licensingservice